//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANG_HOA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HANG_HOA()
        {
            this.BANG_KE_NHAP_HANG = new HashSet<BANG_KE_NHAP_HANG>();
            this.BANG_KE_XUAT_HANG = new HashSet<BANG_KE_XUAT_HANG>();
            this.PHIEU_NHAP = new HashSet<PHIEU_NHAP>();
            this.PHIEU_XUAT = new HashSet<PHIEU_XUAT>();
            this.PHIEU_XUAT_KHO = new HashSet<PHIEU_XUAT_KHO>();
        }
    
        public string MA_HH { get; set; }
        public string TEN_HH { get; set; }
        public string MA_NCC { get; set; }
        public Nullable<int> GIA_NHAP { get; set; }
        public Nullable<int> GIA_XUAT { get; set; }
        public Nullable<int> SO_LUONG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANG_KE_NHAP_HANG> BANG_KE_NHAP_HANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANG_KE_XUAT_HANG> BANG_KE_XUAT_HANG { get; set; }
        public virtual NHA_CUNG_CAP NHA_CUNG_CAP { get; set; }
        public virtual NHAP_XUAT_TON NHAP_XUAT_TON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEU_NHAP> PHIEU_NHAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEU_XUAT> PHIEU_XUAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEU_XUAT_KHO> PHIEU_XUAT_KHO { get; set; }
        public virtual TON_DAU_KY TON_DAU_KY { get; set; }
    }
}
