//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho_FAST
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLKHOEntities : DbContext
    {
        public QLKHOEntities()
            : base("name=QLKHOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BANG_KE_NHAP_HANG> BANG_KE_NHAP_HANG { get; set; }
        public virtual DbSet<BANG_KE_XUAT_HANG> BANG_KE_XUAT_HANG { get; set; }
        public virtual DbSet<HANG_HOA> HANG_HOA { get; set; }
        public virtual DbSet<KHO> KHOes { get; set; }
        public virtual DbSet<NHA_CUNG_CAP> NHA_CUNG_CAP { get; set; }
        public virtual DbSet<NHAN_VIEN> NHAN_VIEN { get; set; }
        public virtual DbSet<NHAP_XUAT_TON> NHAP_XUAT_TON { get; set; }
        public virtual DbSet<PHIEU_NHAP> PHIEU_NHAP { get; set; }
        public virtual DbSet<PHIEU_XUAT> PHIEU_XUAT { get; set; }
        public virtual DbSet<PHIEU_XUAT_KHO> PHIEU_XUAT_KHO { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TON_DAU_KY> TON_DAU_KY { get; set; }
    }
}
