//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAP_XUAT_TON
    {
        public string MA_HH { get; set; }
        public Nullable<int> TON_DAU { get; set; }
        public Nullable<int> NHAP { get; set; }
        public Nullable<int> XUAT { get; set; }
        public Nullable<int> TON_CUOI { get; set; }
    
        public virtual HANG_HOA HANG_HOA { get; set; }
    }
}
