//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEU_NHAP_HH
    {
        public int SOCHUNGTU { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
        public string MANCC { get; set; }
        public string MAHH { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<int> GIA { get; set; }
        public Nullable<int> TIEN { get; set; }
        public string DIENGIAI { get; set; }
    }
}
