//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho_FAST
{
    using System;
    using System.Collections.Generic;
    
    public partial class TON_DAU_KY
    {
        public string MA_HH { get; set; }
        public Nullable<int> SO_LUONG { get; set; }
        public Nullable<int> DON_GIA { get; set; }
        public Nullable<System.DateTime> NGAY_TINH { get; set; }
    
        public virtual HANG_HOA HANG_HOA { get; set; }
    }
}
